### ISSUE TITLE
Cant debug this error Uncaught exception 'SSRS\SSRSReportException'

### ISSUE THREAD

**Issue by felipecorrea9** [EmergencyReporting/ssrsreport#3]
I have tried to debug this, printing the arrays but, there is nothing that could point me to something clear.

So Ifar I have been able to login correctly to SSRS using de SDK, but I havent been able to use the GetReports.php to load a sigle one.
Im passing the report path using GET.

Fatal error: Uncaught exception 'SSRS\SSRSReportException' in C:\xampp\xampplite\htdocs\vendor\ercorp\ssrs-sdk\library\SSRS\SSRSType\SSRSBaseType.php:81 Stack trace: #0 C:\xampp\xampplite\htdocs\vendor\ercorp\ssrs-sdk\library\SSRS\SSRSType\ReportParameterCollection.php(53): SSRS\SSRSType\SSRSBaseType->FromStdObject_Base('self', Array) #1 C:\xampp\xampplite\htdocs\vendor\ercorp\ssrs-sdk\library\SSRS\Factory\SSRSTypeFactory.php(89): SSRS\SSRSType\ReportParameterCollection->FromStdObject(Object(stdClass)) #2 C:\xampp\xampplite\htdocs\vendor\ercorp\ssrs-sdk\library\SSRS\SSRSReport.php(236): SSRS\Factory\SSRSTypeFactory::CreateSSRSObject('ReportParameter...', Object(stdClass)) #3 C:\xampp\xampplite\htdocs\GetReports.php(81): SSRS\SSRSReport->GetReportParameters('/Reportes/DesCo...', NULL, true, NULL, NULL) #4 {main} thrown in C:\xampp\xampplite\htdocs\vendor\ercorp\ssrs-sdk\library\SSRS\SSRSType\SSRSBaseType.php on line 81

**Comment by TheArtOfPour** [comment]
Are you able to provide a code sample for repro?
